### ISSUE TITLE
Convert your ER model to a set of schemas. 

### ISSUE THREAD

**Issue by dulbrich** [dulbrich/conference-database#4]

**Comment by dulbrich** [comment]
I haven't committed this yet. But I have this done.

**Comment by dulbrich** [comment]
Done.

**Comment by DRKPI** [comment]
Uploaded the new ER diagram and schema. These do exactly what our original
database does. My friend just took out duplicates and made the joins work
smoother. We need to check the normal forms now but hopefully they are
pretty good.

David K

2017-03-27 13:14 GMT-06:00 David Ulbrich <notifications@github.com>:
